### ISSUE TITLE
1.19.2 weak_generator crash

### ISSUE THREAD

**Issue by gundami** [nullTheCoder/create-electric-stonks#3]
weak_generator may crash the game, this is the crash report
https://paste.ubuntu.com/p/4VX8zrn7CT/

**Comment by nullTheCoder** [comment]
Thank you for reporting this issue.

The root of the issue was that for some reason I was creating efficiencies map only on client side (Probably wrote that code while being half asleep).

This also means that it would only crush if you are using a standalone server without a craft tweaker script running init.
